function(fri3d_set_loglevel)
    if (CONFIG_FRI3D_LOG_INFO)
        target_compile_definitions(${COMPONENT_LIB} PUBLIC "-DLOG_LOCAL_LEVEL=ESP_LOG_INFO")
    elseif (CONFIG_FRI3D_LOG_DEBUG)
        target_compile_definitions(${COMPONENT_LIB} PUBLIC "-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG")
    elseif (CONFIG_FRI3D_LOG_VERBOSE)
        target_compile_definitions(${COMPONENT_LIB} PUBLIC "-DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE")
    endif ()
endfunction()
